//! JIT compilation support for Oscen graphs using Cranelift
//!
//! This module provides Just-In-Time compilation of audio graphs to machine code,
//! enabling CMajor-level performance (10-20x speedup) while maintaining runtime
//! flexibility for dynamic graph repatching.
//!
//! # Architecture
//!
//! The JIT compiler works by:
//! 1. Taking a runtime-built `Graph`
//! 2. Computing its topology (processing order)
//! 3. Generating Cranelift IR for each node
//! 4. Emitting connection routing as direct memory copies
//! 5. Compiling to native machine code
//! 6. Returning a function pointer for fast execution
//!
//! When the graph is modified (nodes added, connections changed), the compiled
//! code is invalidated and recompiled on the next `process()` call.
//!
//! # Example
//!
//! ```no_run
//! use oscen::jit::JITGraph;
//! use oscen::{Oscillator, Gain};
//!
//! let mut graph = JITGraph::new(44100.0);
//!
//! let osc = graph.add_node(Oscillator::sine(440.0, 0.5));
//! let gain = graph.add_node(Gain::new(0.8));
//!
//! graph.connect(osc.output, gain.input);
//!
//! // First call triggers JIT compilation
//! let output = graph.process(); // ~10-20x faster than interpreted!
//!
//! // Modify graph - invalidates compiled code
//! graph.set_value(gain.gain, 0.5);
//! // Next process() will recompile automatically
//! ```

mod compiler;
mod codegen;
mod memory_layout;
mod jit_graph;

pub use compiler::JITCompiler;
pub use codegen::{NodeCodegen, CodegenContext};
pub use memory_layout::{MemoryLayout, NodeOffsets};
pub use jit_graph::{JITGraph, JITError};

/// Type alias for compiled graph function pointer
///
/// # Safety
///
/// The function pointer is generated by Cranelift and must be called with
/// valid pointers to the graph's state, IO, and parameter buffers.
pub type CompiledGraphFn = unsafe extern "C" fn(
    state_ptr: *mut u8,
    io_ptr: *mut u8,
    params_ptr: *const u8,
    sample_rate: f32,
) -> f32;
