[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
license = "ISC"
description = "A helper for compiling and bundling plugins, can be invoked in this repo using `cargo xtask`"

[dependencies]
nih_plug_xtask = { git = "https://github.com/robbert-vdh/nih-plug" }