//! Pre-designed coefficients for the resampler kernels.
//!
//! All halfband filters here are linear-phase, symmetric, with center tap 0.5
//! and even-indexed off-center taps equal to zero. We store only the non-zero
//! taps for one half of the filter.

/// Half of the non-zero taps for a 23-tap Kaiser-windowed halfband FIR
/// (β ≈ 8.6). Stopband ≈ −90 dB above 0.55 π, passband ripple ≈ ±0.01 dB
/// below 0.45 π. Generated by `scipy.signal.firwin(23, 0.5, window=("kaiser", 8.6))`
/// then keeping only taps at indices 0, 2, 4, ..., 10 (the rest are 0 except center=0.5).
///
/// Layout: `HALFBAND_23_HALF[k]` is the tap at index `2*k` of the full filter,
/// for k = 0..6. The center tap (index 11) is always 0.5 and stored separately.
pub const HALFBAND_23_HALF: [f32; 6] = [
    -0.000_117_8,
     0.001_853_2,
    -0.012_167_5,
     0.043_775_4,
    -0.121_924_3,
     0.405_770_3,
];

/// The center (index 11) tap of the 23-tap halfband.
pub const HALFBAND_23_CENTER: f32 = 0.5;

/// Number of non-zero taps (in the half-filter) before the center tap.
pub const HALFBAND_23_HALF_LEN: usize = HALFBAND_23_HALF.len();

/// Group delay of the 23-tap halfband, measured at the high (2×) rate, in samples.
/// Equal to (filter order) / 2 = 22 / 2 = 11.
pub const HALFBAND_23_GROUP_DELAY: usize = 11;

/// IIR halfband: two-branch all-pass cascade.
///
/// Branch A: a0(z) = (b + z^-2) / (1 + b * z^-2), with b = BRANCH_A_BETAS[k]
/// Branch B: same form, with b = BRANCH_B_BETAS[k]
/// Output = 0.5 * (A(z) + z^-1 * B(z))
///
/// Coefficients chosen for ~80 dB stopband above 0.6 π. From Regalia/Mitra
/// "Tunable digital frequency response equalization filters" reference design.
pub const BRANCH_A_BETAS: [f32; 2] = [0.061_273_4, 0.484_801_0];
pub const BRANCH_B_BETAS: [f32; 2] = [0.234_087_5, 0.795_217_5];

/// Approximate group delay of the IIR halfband at center band, in source samples.
pub const IIR_HALFBAND_GROUP_DELAY: usize = 4;
