//! Pre-designed coefficients for the resampler kernels.
//!
//! All halfband filters here are linear-phase, symmetric, with center tap 0.5
//! and even-indexed off-center taps equal to zero. We store only the non-zero
//! taps for one half of the filter.

/// Half of the non-zero taps for a 23-tap Kaiser-windowed halfband FIR
/// (β ≈ 8.6). Stopband ≈ −90 dB above 0.55 π, passband ripple ≈ ±0.01 dB
/// below 0.45 π. Generated by `scipy.signal.firwin(23, 0.5, window=("kaiser", 8.6))`
/// then keeping only taps at indices 0, 2, 4, ..., 10 (the rest are 0 except center≈0.5).
///
/// Layout: `HALFBAND_23_HALF[k]` is the tap at index `2*k` of the full filter,
/// for k = 0..6. The center tap (index 11) is stored separately.
///
/// Sum of all filter taps = 1 (DC gain 1 when used as a downsample FIR; the
/// upsampler must scale by 2 to compensate for zero-stuffing).
pub const HALFBAND_23_HALF: [f32; 6] = [
    -3.855_851_4e-5,
     1.221_846_5e-3,
    -7.285_480_8e-3,
     2.640_921_0e-2,
    -7.812_884_3e-2,
     3.078_269_7e-1,
];

/// The center (index 11) tap of the 23-tap halfband.
pub const HALFBAND_23_CENTER: f32 = 0.499_989_7;

/// Number of non-zero taps (in the half-filter) before the center tap.
pub const HALFBAND_23_HALF_LEN: usize = HALFBAND_23_HALF.len();

/// Group delay of the 23-tap halfband, measured at the high (2×) rate, in samples.
/// Equal to (filter order) / 2 = 22 / 2 = 11.
pub const HALFBAND_23_GROUP_DELAY: usize = 11;

/// IIR halfband: two-branch all-pass cascade in polyphase form.
///
/// Each branch is a cascade of 1st-order all-pass sections of the form
/// `(a + z^-1) / (1 + a * z^-1)` operating at the LOW (post-decimation) rate.
/// The high-rate transfer function is
/// `H(z) = 0.5 * (A(z^2) + z^-1 * B(z^2))`
/// where `A(z) = prod_k (BRANCH_A_BETAS[k] + z^-1) / (1 + BRANCH_A_BETAS[k]*z^-1)`
/// and similarly for `B`.
///
/// Coefficients found by min-max optimisation of the stopband for f > 0.27
/// (high-rate cycles/sample): passband flat to within ~0.001 dB below 0.20
/// and stopband below −49 dB above 0.27.
pub const BRANCH_A_BETAS: [f32; 2] = [0.135_574_1, 0.697_584_9];
pub const BRANCH_B_BETAS: [f32; 2] = [0.425_380_4, 0.905_560_1];

/// Approximate group delay of one 2× IIR halfband stage, measured at the
/// HIGH rate, in samples. The optimised 4-coefficient design has a group
/// delay near 2 high-rate samples around DC.
pub const IIR_HALFBAND_GROUP_DELAY: usize = 2;
