use super::traits::{ProcessingContext, SignalProcessor};
use super::{InputEndpoint, NodeKey, ProcessingNode, ValueKey};
use crate::Node;

/// AudioInput node with direct field access.
#[derive(Debug, Node)]
pub struct AudioInput {
    #[input]
    input_value: f32,  // Value input (stays in graph state)

    #[output(stream)]
    pub output: f32,  // Direct access!
}

impl AudioInput {
    pub fn new() -> Self {
        Self {
            input_value: 0.0,
            output: 0.0,
        }
    }
}

impl Default for AudioInput {
    fn default() -> Self {
        Self::new()
    }
}

impl AudioInput {
    /// Core processing logic
    #[inline]
    pub fn process(&mut self, _sample_rate: f32) -> f32 {
        // Output field is populated directly
        self.output
    }
}

impl SignalProcessor for AudioInput {
    /// Auto-generated by macro, but we override to get value input and call our process().
    fn process<'a>(&mut self, sample_rate: f32, context: &mut ProcessingContext<'a>) -> f32 {
        // Get value input from graph and write to output
        self.output = self.get_input_value(context);

        // Call core processing logic
        AudioInput::process(self, sample_rate)
    }
}
