use arrayvec::ArrayVec;

use super::types::NodeKey;
use super::types::{
    EndpointDescriptor, EventInstance, ValueData, ValueKey, ValueObject,
    MAX_NODE_ENDPOINTS, MAX_STREAM_CHANNELS,
};

#[derive(Copy, Clone)]
pub struct ValueRef<'a> {
    data: &'a ValueData,
}

impl<'a> ValueRef<'a> {
    pub(crate) fn new(data: &'a ValueData) -> Self {
        Self { data }
    }

    pub fn as_scalar(&self) -> Option<f32> {
        self.data.as_scalar()
    }

    pub fn as_object(&self) -> Option<&'a dyn ValueObject> {
        self.data.as_object()
    }

    pub fn data(&self) -> &'a ValueData {
        self.data
    }
}

pub struct ProcessingContext<'a> {
    stream_inputs: &'a [ArrayVec<f32, MAX_STREAM_CHANNELS>],
    value_inputs: &'a [Option<&'a ValueData>],
    event_inputs: &'a [&'a [EventInstance]],
}

impl<'a> ProcessingContext<'a> {
    pub fn new(
        stream_inputs: &'a [ArrayVec<f32, MAX_STREAM_CHANNELS>],
        value_inputs: &'a [Option<&'a ValueData>],
        event_inputs: &'a [&'a [EventInstance]],
    ) -> Self {
        Self {
            stream_inputs,
            value_inputs,
            event_inputs,
        }
    }

    #[inline]
    pub fn stream(&self, index: usize) -> f32 {
        self.stream_inputs
            .get(index)
            .and_then(|channels| channels.first())
            .copied()
            .unwrap_or(0.0)
    }

    #[inline]
    pub fn stream_channels(&self, index: usize) -> &[f32] {
        self.stream_inputs
            .get(index)
            .map(|channels| channels.as_slice())
            .unwrap_or(&[])
    }

    #[inline]
    pub fn value(&self, index: usize) -> Option<ValueRef<'a>> {
        self.value_inputs
            .get(index)
            .and_then(|opt| opt.map(ValueRef::new))
    }

    #[inline]
    pub fn value_scalar(&self, index: usize) -> f32 {
        self.value(index)
            .and_then(|value| value.as_scalar())
            .unwrap_or_else(|| self.stream(index))
    }

    #[inline]
    pub fn events(&self, index: usize) -> &[EventInstance] {
        self.event_inputs.get(index).copied().unwrap_or_default()
    }
}

/// Trait for safe, type-erased access to IO struct fields.
/// This enables the graph to read outputs and write inputs without knowing the concrete IO struct type.
/// Implementations are generated by the #[derive(Node)] macro.
pub trait IOStructAccess: Send {
    /// Get the number of stream inputs
    fn num_stream_inputs(&self) -> usize;

    /// Get the number of stream outputs
    fn num_stream_outputs(&self) -> usize;

    /// Get the number of event outputs
    fn num_event_outputs(&self) -> usize;

    /// Set a stream input field (graph writes here before processing)
    fn set_stream_input(&mut self, index: usize, value: f32);

    /// Get a stream input field value (node reads during processing)
    fn get_stream_input(&self, index: usize) -> Option<f32>;

    /// Set a stream output field (node writes during processing)
    fn set_stream_output(&mut self, index: usize, value: f32);

    /// Get a stream output field value (graph reads after processing to route)
    fn get_stream_output(&self, index: usize) -> Option<f32>;

    /// Set multi-channel stream input (for arrays/multi-channel streams)
    fn set_stream_input_channels(&mut self, index: usize, channels: &[f32]) {
        // Default: set first channel only for backward compatibility
        if let Some(&first) = channels.first() {
            self.set_stream_input(index, first);
        }
    }

    /// Get multi-channel stream output (returns channels as slice)
    fn get_stream_output_channels(&self, _index: usize) -> &[f32] {
        // Default: return empty slice (no multi-channel support)
        &[]
    }

    /// Get event output instances (used after node processing to route events)
    fn get_event_output(&self, index: usize) -> &[EventInstance];

    /// Clear all event output buffers (called before each processing cycle)
    fn clear_event_outputs(&mut self);
}

/// Users implement this trait to define their DSP logic. Inputs are already
/// populated in the struct fields by the time process() is called.
pub trait SignalProcessor: Send + std::fmt::Debug {
    /// Called once when the node is added to a graph.
    fn init(&mut self, _sample_rate: f32) {}

    /// Process one sample of audio.
    ///
    /// All inputs are already populated in struct fields. Write outputs to
    /// output fields. No context object to deal with!
    ///
    /// Sample rate is stored in the node during init() or construction.
    /// For static graphs, this is called directly with zero overhead.
    /// For runtime graphs, NodeIO::read_inputs() is called first to populate inputs.
    fn process(&mut self);

    /// Whether this node can break feedback cycles (e.g., delay lines).
    #[inline]
    fn allows_feedback(&self) -> bool {
        false
    }

    /// Returns whether this node is currently active and producing meaningful output.
    /// Inactive nodes can be skipped during processing, with their outputs set to 0.0.
    #[inline]
    fn is_active(&self) -> bool {
        true
    }
}

/// Node IO trait - handles reading inputs from context and providing outputs.
/// This is auto-generated by the #[derive(Node)] macro.
pub trait NodeIO {
    /// Read all inputs from the processing context into struct fields.
    /// Called by runtime graphs before process().
    fn read_inputs<'a>(&mut self, context: &mut ProcessingContext<'a>);

    /// Get stream output value by index (for runtime graph routing).
    #[inline]
    fn get_stream_output(&self, _index: usize) -> Option<f32> {
        None
    }

    /// Set stream input value by index (for runtime graph routing).
    #[inline]
    fn set_stream_input(&mut self, _index: usize, _value: f32) {
        // Default: do nothing
    }

    /// Get multi-channel stream output (returns channels as slice)
    #[inline]
    fn get_stream_output_channels(&self, _index: usize) -> &[f32] {
        &[]
    }

    /// Set multi-channel stream input
    #[inline]
    fn set_stream_input_channels(&mut self, index: usize, channels: &[f32]) {
        // Default: set first channel only for backward compatibility
        if let Some(&first) = channels.first() {
            self.set_stream_input(index, first);
        }
    }

    /// Get value output by index (for runtime graph routing).
    #[inline]
    fn get_value_output(&self, _index: usize) -> Option<ValueData> {
        None
    }
}

/// Marker trait for nodes that can be processed in the runtime graph.
/// Implemented by the #[derive(Node)] macro.
pub trait DynNode: SignalProcessor + NodeIO {
    /// Optional array event routing. Returns None if this node doesn't support it.
    /// Nodes that implement ArrayEventOutput should override this.
    fn route_event(&mut self, _input_index: usize, _event: &EventInstance) -> Option<usize> {
        None
    }
}

/// Trait for nodes that route events to array outputs at runtime.
/// Inspired by CMajor's `voiceEventOut[index] <- event` pattern.
///
/// Nodes like VoiceAllocator implement this to provide runtime multiplexing:
/// incoming events are routed to different output indices based on runtime state
/// (e.g., voice allocation, round-robin, etc.).
pub trait ArrayEventOutput {
    /// Process an event from the given input and return which output index to route it to.
    /// Returns None if the event should not be routed.
    ///
    /// # Arguments
    /// * `input_index` - Which input endpoint the event arrived at (e.g., 0 for note_on, 1 for note_off)
    /// * `event` - The event to process
    fn route_event(&mut self, input_index: usize, event: &EventInstance) -> Option<usize>;
}

/// Helper trait to expose ArrayEventOutput through type erasure.
/// This allows us to call route_event on Box<dyn DynNode> when needed.
#[allow(dead_code)]
pub trait DynArrayEventOutput: DynNode + ArrayEventOutput {}

// Automatic implementation for all types that implement both DynNode and ArrayEventOutput
impl<T: DynNode + ArrayEventOutput> DynArrayEventOutput for T {}

pub trait ProcessingNode: SignalProcessor + NodeIO {
    type Endpoints;

    const ENDPOINT_DESCRIPTORS: &'static [EndpointDescriptor] = &[];

    /// Factory function to create IO struct for this node type.
    /// Generated by #[derive(Node)] macro, returns node-specific IO struct.
    /// Default panics - must be overridden by derive macro.
    const CREATE_IO_FN: fn() -> Box<dyn IOStructAccess> =
        || panic!("CREATE_IO_FN not implemented - use #[derive(Node)] macro");

    fn create_endpoints(
        node_key: NodeKey,
        inputs: ArrayVec<ValueKey, MAX_NODE_ENDPOINTS>,
        outputs: ArrayVec<ValueKey, MAX_NODE_ENDPOINTS>,
    ) -> Self::Endpoints;

    /// Returns initial values for value inputs as (input_index, value) pairs.
    /// Called during node addition to initialize graph endpoints from constructor arguments.
    fn default_values(&self) -> Vec<(usize, f32)> {
        vec![]
    }
}
