[package]
name = "oscen2"
version = "0.1.0"
edition = "2021"

[dependencies]
oscen2-macros = { path = "../oscen2-macros" }
arrayvec = "0.7.6"
cpal = "0.15.3"
hound = "3.5.1"
slotmap = "1.0.7"

[dev-dependencies]
float-cmp = "0.10.0"