use crate::graph::{InputEndpoint, NodeKey, ProcessingNode, ValueKey};
use crate::Node;

/// Gain node with direct field access - clean and intuitive!
///
/// The #[derive(Node)] macro generates:
/// - GainIO struct: holds stream I/O (for backward compatibility)
/// - GainEndpoints: typed endpoint handles
/// - SignalProcessor impl that populates stream fields from context
/// - process_internal() wrapper for compile-time graphs
///
/// Stream fields (input, output) hold runtime values - wire them directly!
#[derive(Debug, Node)]
pub struct Gain {
    #[input(stream)]
    pub input: f32,      // Runtime value - wire directly!

    #[input(value)]
    pub gain: f32,

    #[output(stream)]
    pub output: f32,     // Runtime value - wire directly!
}

impl Gain {
    pub fn new(initial_gain: f32) -> Self {
        Self {
            input: 0.0,
            gain: initial_gain,
            output: 0.0,
        }
    }

    /// Core processing logic - auto-wrapped by the Node macro.
    ///
    /// The #[derive(Node)] macro automatically generates:
    /// - SignalProcessor::process() trait impl that populates stream fields from context
    /// - process_internal() wrapper for compile-time graphs
    /// Both wrappers call THIS method using fully qualified syntax.
    ///
    /// This is the ONLY place where processing logic needs to be written!
    #[inline]
    pub fn process(&mut self, _sample_rate: f32) -> f32 {
        // Stream fields are already populated (by macro wrapper or direct wiring)
        self.output = self.input * self.gain;
        self.output
    }
}

impl Default for Gain {
    fn default() -> Self {
        Self::new(1.0)
    }
}

// SignalProcessor and process_internal() are now auto-generated by #[derive(Node)]!
