use crate::graph::{InputEndpoint, NodeKey, ProcessingNode, ValueKey};
use crate::Node;

/// Gain node using struct-of-arrays IO pattern.
///
/// The #[derive(Node)] macro generates:
/// - GainIO struct: holds stream I/O (input, output fields)
/// - GainEndpoints: typed endpoint handles
///
/// State (this struct): holds persistent data and value inputs
/// IO (generated GainIO): holds per-sample stream data
#[derive(Debug, Node)]
pub struct Gain {
    #[input(stream)]
    input: f32,

    #[input(value)]
    gain: f32,

    #[output(stream)]
    output: f32,

    /// Persistent IO struct - reused every call for zero overhead.
    /// Public so compile-time graphs can wire connections directly.
    pub io: GainIO,
}

impl Gain {
    pub fn new(initial_gain: f32) -> Self {
        Self {
            input: 0.0,      // Placeholder for endpoint descriptor
            gain: initial_gain,  // Initial value for gain parameter
            output: 0.0,     // Placeholder for endpoint descriptor
            io: GainIO {
                input: 0.0,
                output: 0.0,
            },
        }
    }

    /// Core processing logic - auto-wrapped by the Node macro.
    ///
    /// The #[derive(Node)] macro automatically generates:
    /// - process() method that populates self.io from context and calls this
    /// - process_internal() method for compile-time graphs
    ///
    /// This is the ONLY place where processing logic needs to be written!
    #[inline]
    pub fn compute(&mut self, _sample_rate: f32) -> f32 {
        // self.io is already populated (either by macro-generated process(), or by direct wiring)
        self.io.output = self.io.input * self.gain;
        self.io.output
    }
}

impl Default for Gain {
    fn default() -> Self {
        Self::new(1.0)
    }
}

// SignalProcessor and process_internal() are now auto-generated by #[derive(Node)]!
